"""
- REDUCE IS USED TO GET THE RESULT OF ANY OPERATION ON THE ITERABLE OBJECT BUT IN THE FORM OF INTEGER OR AS SINGLE ELEMENT
- REDUCE PERFORM THE GIVEN FUNCTION ON ITERABLE AND RETURN THE OUTPUT AS SINGLE ELEMENT
- REDUCE PERFORM THE OPERATION ON ALL ELEMENTS OF ITERABLE AND RETURN A SINGLE ELEMENT

- SYNTAX IS SAME AS MAP, FILTER FUNCTION.
        OBJ NAME = filter(function name/lambda, iterable name)

- TO USE REDUCE WE HAVE TO IMPORT FUNC TOOLS
"""

